- CHANGELOG.md
- cmd/groundcover/api_key.go
- cmd/groundcover/auth.go
- cmd/groundcover/login.go
- install.sh
Gitbook CR: https://app.gitbook.com/o/s7NGqhkKawIAiqSm9PSn/s/UHgqKYgCiRKdOpWQdi52/~/changes/ACJSG9NqS5NFG5s1jlYh/install-groundcover/installation
> [sc-4121] add print-api-key and login as subcommand of auth

- Earthfile
The build-cli target failed building the cli tool, due to project structure changes. Fixed
> [sc-4564] - fixed earthfile build-cli issue

- CHANGELOG.md
Story details: https://app.shortcut.com/groundcover/story/7825
> feat: [sc-7825] cli release 0.8.7

- CHANGELOG.md
- pkg/helm/presets/backend/high-resources.yaml
- pkg/helm/presets/backend/low-resources.yaml
- pkg/helm/presets/backend/medium-resources.yaml
Reverts groundcover-com/cli#200
> Revert "[sc-8227] loki ingestion rate limit tuning"

- pkg/helm/presets/backend/low-resources.yaml
Story details: https://app.shortcut.com/groundcover/story/8658
> fix: [sc-8658] otel low resources increase limits

- CHANGELOG.md
Story details: https://app.shortcut.com/groundcover/story/8660
> feat: [sc-8660] release 0.9.8

- cmd/status.go
- pkg/helm/presets/backend/emptydir-storage.yaml
- pkg/helm/presets/backend/high-resources.yaml
- pkg/helm/presets/backend/low-resources.yaml
- pkg/helm/presets/backend/medium-resources.yaml
Story details: https://app.shortcut.com/groundcover/story/9560
> [sc-9560] remove timescaledb mentions

- CHANGELOG.md
Story details: https://app.shortcut.com/groundcover/story/9747
> feat: [sc-9747] cli 0.10.6

- CHANGELOG.md
Reverts groundcover-com/cli#235
> Revert "feat: [sc-9747] cli 0.10.6"

- pkg/segment/user.go
Story details: https://app.shortcut.com/groundcover/story/9870
> feat: [sc-9870] add email to grouping event

- CHANGELOG.md
Story details: https://app.shortcut.com/groundcover/story/9871
> feat: [sc-9871] release 0.10.8

- pkg/segment/user.go
Story details: https://app.shortcut.com/groundcover/story/9938
> fix: [sc-9938] move to sha256 in user

- CHANGELOG.md
Story details: https://app.shortcut.com/groundcover/story/9946
> feat: [sc-9946] release 0.10.9

- pkg/k8s/cluster_test.go
- pkg/k8s/storage.go
Story details: https://app.shortcut.com/groundcover/story/10131
> fix: [sc-10131] support storageclass beta annotation

- CHANGELOG.md
Story details: https://app.shortcut.com/groundcover/story/10138
> feat: [sc-10138] release 0.10.11

- CHANGELOG.md
- cmd/deploy.go
- pkg/helm/presets/backend/custom-metrics.yaml
- pkg/helm/presets/backend/kube-state-metrics.yaml
Deploy kube-state-metrics and custom metrics scraping by default
> [sc-10432] - enable ksm by default

- CHANGELOG.md
Story details: https://app.shortcut.com/groundcover/story/10714
> feat: [sc-10714] release 0.10.13

- pkg/helm/presets/backend/low-resources.yaml
Story details: https://app.shortcut.com/groundcover/story/10885
> feat: [sc-10885] cli - change mini values

- CHANGELOG.md
Story details: https://app.shortcut.com/groundcover/story/10890
> feat: [sc-10890] release 0.10.14

- CHANGELOG.md
- cmd/deploy.go
- pkg/helm/presets/backend/kube-state-metrics.yaml
Reverted the https://github.com/groundcover-com/cli/pull/254 PR, now ksm is disabled by default with an optional flag for enable.
> [sc-10892] - ksm disabled by default

- pkg/helm/presets/backend/high-resources.yaml
- pkg/helm/presets/backend/huge-resources.yaml
- pkg/helm/presets/backend/low-resources.yaml
Story details: https://app.shortcut.com/groundcover/story/11513
> feat(onboarding): [sc-11513] increase k8swatcher memory limit

- CHANGELOG.md
Story details: https://app.shortcut.com/groundcover/story/11583
> Release 0.10.16

- CHANGELOG.md
- cmd/get_datasources_api_key.go
- pkg/api/client.go
- pkg/api/cluster.go
- pkg/api/tenant.go
- pkg/auth/api_key.go
Added get datasources API key command to cli
> [sc-11671] - add get datasources api key command
